<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\field\Entity\FieldStorageConfig;
use Drupal\field\Entity\FieldConfig;
use Drupal\node\Entity\Node;
use Drupal\node\NodeInterface;
use Drupal\user\Entity\User;
use Symfony\Component\HttpFoundation\RedirectResponse;

use Drupal\ish_drupal_module\Helpers\BjjcHelper;
use Drupal\ish_drupal_module\Helpers\MainHelper;
use Drupal\ish_drupal_module\Controllers\YoutubeChannelCtrl;
use Drupal\ish_drupal_module\Models\PageYoutube;
use Drupal\ish_drupal_module\Models\YoutubeVideo;

function logg($object, $label=null) {
  print($label . ":");
  echo "<br />";
  dump($object);
}

function puts($object, $label=null) {
  print($label . ":");
  echo "<br />";
  dump($object);
}


/*
 *
**/
function ish_drupal_module_cron() {
  \Drupal::logger('ish_drupal_module')->notice('Starting cron...');

  // for piousbox_com as a magazine
  $service = new PageYoutube();
  $service->run_cron();
}

/*
 * renders a different form_display for aphorisms (old, not tested)
**/
function ish_drupal_module_entity_form_display_alter(Drupal\Core\Entity\Entity\EntityFormDisplay &$form_display, array $context) {
  if (in_array('authenticated', \Drupal::currentUser()->getRoles()) &&
      $context['entity_type'] === 'node' &&
      $context['bundle'] === 'aphorism') {
    $storage = \Drupal::entityTypeManager()->getStorage('entity_form_display');
    $differentDisplay = $storage->load("{$context['entity_type']}.{$context['bundle']}.contribute"); // 'my_form_display' was created via /admin/structure/display-modes/form
    if ($differentDisplay) {
      $form_display = $differentDisplay;
    }
  }
}

/*
 * trash, remove?! 2025-10-01
**/
function ish_drupal_module_entity_type_build(array &$entity_types) {
  $entity_types['node']->setFormClass('for_youtube', 'Drupal\node\NodeForm');
  // $entity_types['node']->setFormClass('for_youtube', 'ForYoutube');
}





/*
 * Implements hook_theme().
 *
 * See: https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Render%21theme.api.php/function/hook_theme/8.2.x
 *
 * If you change this method, clear theme registry and routing
 * table 'drush cc theme-registry' and 'drush cc router'.
**/
function ish_drupal_module_theme($existing, $type, $theme, $path) {

  return [
    'error_404' => [
      'render element' => 'children',
      'template' => 'error_404',
      'path' => $path . '/templates',
      'variables' => [],
    ],
    'ish_dance_instructor_dashboard' => [
      'template' => 'dance-instructor-dashboard',
      'path' => $path . '/templates/users',
      'variables' => [
      ],
    ],
    'ish_hiring_manager_dashboard' => [
      'template' => 'hiring-manager-dashboard',
      'path' => $path . '/templates/users',
      'variables' => [
      ],
    ],
    'ish_users_dashboard' => [
      'template' => 'dashboard',
      'path' => $path . '/templates/users',
      'variables' => [
        'for_youtube_form' => NULL,
        'menu_secondary'   => NULL,
      ],
    ],
    'ish_users_edit' => [
      'template' => 'edit',
      'path' => $path . '/templates/users',
      'variables' => [
      ],
    ],
    'ish_locations_show' => [
      // 'render element' => 'requirements',
      'template' => 'show',
      'path' => $path . '/templates/locations',
      'variables' => [
        'location' => NULL,
        // 'request' => NULL,
      ],
    ],


    'menu_user_authenticated' => [
      'path' => $path . '/templates',
      // 'render element' => 'children',
      'template' => 'menu_user_authenticated',
      'variables' => [
        'testvar' => NULL,
      ],
    ],

    'my_feed' => [
      'path' => $path . '/templates',
      'render element' => 'elements', // works?!
      'template' => 'my_feed',
      'variables' => [
        'test_var_1' => null,
      ],
    ],

    'scrape_zerohedge_all' => [
      'render element' => 'children',
      'template' => 'all',
      'path' => $path . '/templates/scrape_zerohedge',
      'variables' => [
        'contents' => 'no contents',
      ],
    ],
    'scrape_zerohedge_one' => [
      'render element' => 'children',
      'template' => 'one',
      'path' => $path . '/templates/scrape_zerohedge',
      'variables' => [
      ],
    ],

    'tags_show' => [
      'render element' => 'children',
      'template' => 'show',
      'path' => $path . '/templates/tags',
      'variables' => [
        'tag' => null,
        'features' => [],
        'newsitems' => [],
      ],
    ],

    'tags_issue_show' => [
      'render element' => 'children',
      'template' => 'show',
      'path' => $path . '/templates/tags_issue',
      'variables' => [
        'parent_tag' => NULL,
        'tags' => [],
        // 'features' => [],
        // 'newsitems' => [],
      ],
    ],

    'tmp' => [
      'render element' => 'children',
      'template' => 'tmp',
      'path' => $path . '/templates',
      'variables' => [
        'tmp' => null,
      ],
    ],

    'videos_show2' => [
      'template' => 'show2',
      'path' => $path. '/templates/videos',
      'variables' => [
        'content' => NULL,
      ],
    ],

    'youtube_channels_check' => [
      'render element' => 'children',
      'template' => 'check',
      'path' => $path . '/templates/youtube_channels',
      'variables' => [
        'abba' => 'default a',
        'decoded_json' => 'no decoded_json',
        'outs' => [ 'no outs' ],
      ],
    ],
    'youtube_channels_index' => [
      'render element' => 'children',
      'template' => 'index',
      'path' => $path . '/templates/youtube_channels',
      'variables' => [
      ],
    ],

  ];

}

/* Redirect user on login.
 * From: https://drupal.stackexchange.com/questions/195170/redirect-after-user-login
 * Works?!
**/
// function ish_drupal_module_form_user_login_form_alter(&$form, $form_state) {
//   $form['#submit'][] = 'ish_drupal_module_user_login_submit';
// }
/*
 * login redirects to dashboard
**/
// function ish_drupal_module_user_login_submit(&$form, $form_state) {
//   $dashboard_url = Url::fromRoute('ish_drupal_module.users_dashboard');
//   $dance_instructor_dashboard_url = Url::fromRoute('ish_drupal_module.dance_instructor_dashboard');
//   // Check if a destination was set, probably on an exception controller.
//   // @see \Drupal\user\Form\UserLoginForm::submitForm()
//   $request = \Drupal::service('request_stack')->getCurrentRequest();
//   if (!$request->request->has('destination')) {
//     $form_state->setRedirectUrl($dashboard_url);
//   }
//   else {
//     $request->query->set('destination', $request->request->get('destination'));
//   }
// }




/*
 * Alter render arrays (structural changes, fields, content).
**/
function ish_drupal_module_node_view(&$build) {
  /* For bjjcollective_com: related nodes for v2 type of video. */
  BjjcHelper::computeRelatedVideos($build);

  // YoutubeChannelCtrl::show($build);

  // logg($build, 'final build');
}

/*
 * Alter template variables (styling, theming context).
**/
function ish_drupal_module_preprocess_node(array &$variables) {
  MainHelper::computeRelatedArticles($variables); // computes related_articles for Article only.
  YoutubeChannelCtrl::show($variables);
  // $variables['my_custom_variable'] = 'Hello, this is my custom text!';
}

