<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\field\Entity\FieldConfig;
use Drupal\field\Entity\FieldStorageConfig;
use Drupal\node\Entity\Node;
use Drupal\node\Entity\NodeType;
use Drupal\node\NodeInterface;
use Drupal\user\Entity\User;
use Symfony\Component\HttpFoundation\RedirectResponse;

use Drupal\ish_drupal_module\Helpers\MainHelper;
use Drupal\ish_drupal_module\Models\ArticleTranslator;


function logg($object, $label=null) {
  print($label . ":");
  echo "<br />";
  dump($object);
}

function puts($object, $label=null) {
  print($label . ":");
  echo "<br />";
  dump($object);
}


/*
 * the cron
**/
/* function ish_drupal_module_cron() {
  \Drupal::logger('ish_drupal_module')->notice('Starting cron...');

  $service = new PageYoutube();
  $service->run_cron();

  $service = new ArticleTranslator();
  $service->runCron();
} */




/*
 * Theme
 *
**/
function ish_drupal_module_theme($existing, $type, $theme, $path) {

  return [
    'admin_home' => [
      'variables' => [
        'secondary_menu_links' => [],
        'create_content_url' => NULL,
        'recreate_layout_url' => NULL,
        'run_task_url' => NULL,
      ],
      'template' => 'admin_home',
    ],
    'article_translate' => [
      'path' => $path . '/templates/articles',
      'render element' => 'children',
      'template' => 'translate',
      'variables' => [
        'item' => NULL,
      ],
    ],
    'articles_index' => [
      'path' => $path . '/templates/articles',
      'render element' => 'children',
      'template' => 'index',
      'variables' => [
        'items' => [],
        'pager' => NULL,
      ],
    ],

    'block__block_content__type__advanced_block' => [
      'base hook' => 'block',
      'path' => $path . '/templates/block',
    ],
    'block__inline_block__section_callout_parallax' => [
      'base hook' => 'block',
      'path' => $path . '/templates/block',
    ],
    'block__inline_block__section_hero_video' => [
      'base hook' => 'block',
      'path' => $path . '/templates/block',
    ],




    'error_404' => [
      'render element' => 'children',
      'template' => 'error_404',
      'path' => $path . '/templates',
      'variables' => [],
    ],



    'menu_user_authenticated' => [
      'path' => $path . '/templates',
      // 'render element' => 'children',
      'template' => 'menu_user_authenticated',
      'variables' => [
        'testvar' => NULL,
      ],
    ],

    'page__node__issue' => [
      'base hook' => 'page',
      'path' => $path . '/templates/layout',
    ],

    'tmp' => [
      'render element' => 'children',
      'template' => 'tmp',
      'path' => $path . '/templates',
      'variables' => [
        'tmp' => null,
      ],
    ],

  ];

}


function ish_drupal_module_page_attachments(array &$attachments) {
  // $attachments['#attached']['library'][] = 'ish_drupal_module/bootstrap4';
  $attachments['#attached']['library'][] = 'ish_drupal_module/bootstrap5';
  // $attachments['#attached']['library'][] = 'ish_drupal_module/bootstrap5_cdn';
  $attachments['#attached']['library'][] = 'ish_drupal_module/vendor';
  $attachments['#attached']['library'][] = 'ish_drupal_module/main';
  $attachments['#attached']['library'][] = 'ish_drupal_module/collapse_expand';
}


/*
 * compute related articles
**/
function ish_drupal_module_preprocess_node(array &$variables) {
  MainHelper::computeRelatedArticles($variables); // computes related_articles for Article only.
}

