<?php

use Drupal\ish_drupal_module\Config\BlocksConfig;
use Drupal\ish_drupal_module\Config\ContentTypesConfig;
use Drupal\ish_drupal_module\Config\DefaultFields;
use Drupal\ish_drupal_module\Config\LayoutConfig;
use Drupal\ish_drupal_module\Config\ModulesConfig;
use Drupal\ish_drupal_module\Config\SectionsConfig;
use Drupal\ish_drupal_module\Config\ThisConfig;
use Drupal\ish_drupal_module\Config\ViewsConfig;

/*
 * reset the counter:
 *   drush -l mavericks.local php:eval "\Drupal::keyValue('system.schema')->delete('ish_drupal_module');"
 * check the counter:
 *   drush -l mavericks.local php:eval "print \Drupal::keyValue('system.schema')->get('ish_drupal_module');"
**/

/*
**/
function ish_drupal_module_update_9002() {
  ModulesConfig::install_modules();
  ThisConfig::configure_text_editor();
  ThisConfig::setup_permissions();
  ThisConfig::setup_view_modes();
  ThisConfig::setup_tags();
  ThisConfig::setup_views_config();

  ContentTypesConfig::setup_issue();
  ContentTypesConfig::setup_slide();
  ContentTypesConfig::setup_content_type('advanced_page', DefaultFields::default_node_fields );
  ContentTypesConfig::enable_layout_builder_for('advanced_page', 'full');

  LayoutConfig::clear();
  BlocksConfig::hours_of_operation();
  BlocksConfig::copyright();
  LayoutConfig::setup_marketing_site();


  BlocksConfig::create_block_type('advanced_block', DefaultFields::default_block_fields);
  BlocksConfig::setup_about_20();                                        // BlocksConfig::create_block_type('section_about_20', DefaultFields::default_block_fields);
  BlocksConfig::create_block_type('section_about_3cards', DefaultFields::default_block_fields);
  BlocksConfig::create_block_type('section_callout_parallax', DefaultFields::default_block_fields);
  BlocksConfig::create_block_type('section_hero_video', DefaultFields::default_block_fields);
  BlocksConfig::create_block_type('section_list_10', DefaultFields::default_block_fields);
  BlocksConfig::create_block_type('section_slider_images', DefaultFields::default_block_fields);

  BlocksConfig::setup_slider_images();
  BlocksConfig::setup_hero_video();
  BlocksConfig::setup_callout_parallax();

  ViewsConfig::create_from_file('views.view.master.yml');
}

// function ish_drupal_module_update_9013() {
// }






