<?php

use Drupal\Core\Entity\Entity\EntityFormDisplay;
use Drupal\Core\Entity\Entity\EntityViewDisplay;
use Drupal\Core\Entity\Entity\EntityViewMode;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\field\Entity\FieldStorageConfig;
use Drupal\field\Entity\FieldConfig;
use Drupal\node\Entity\Node;
use Drupal\node\Entity\NodeType;
use Drupal\node\NodeInterface;
use Drupal\taxonomy\Entity\Vocabulary;
use Symfony\Component\HttpFoundation\RedirectResponse;

use Drupal\ish_drupal_module\Models\YoutubeChannel;

/*
 * for piousbox_com as a magazine
 * adds field_last_polled_at to youtube_channel
**/
function ish_drupal_module_update_9001() {
  $content_type = 'youtube_channel';
  if (!NodeType::load($content_type)) {
    $type = NodeType::create([
      'type' => $content_type,
      'name' => $content_type,
      'description' => $content_type,
      'display_submitted' => TRUE,
    ]);
    $type->save();
  }

  $field_name = 'field_last_polled_at';
  if (!FieldStorageConfig::loadByName('node', $field_name)) {
    FieldStorageConfig::create([
      'field_name' => $field_name,
      'entity_type' => 'node',
      'type' => 'string',
      'settings' => [
        'max_length' => 20,
      ],
      'cardinality' => 1,
      'translatable' => FALSE,
    ])->save();
  }
  if (!FieldConfig::loadByName('node', $content_type, $field_name)) {
    FieldConfig::create([
      'field_name' => $field_name,
      'entity_type' => 'node',
      'bundle' => $content_type,
      'label' => $field_name,
      'description' => $field_name,
      'required' => FALSE,
      'settings' => [],
    ])->save();
  }
}

/**
 * Migrate article values from field_tag_contrib to field_tags_contrib.
**/
function ish_drupal_module_update_9002() {
  $nids = \Drupal::entityQuery('node')
    ->condition('type', 'article')
    ->accessCheck(FALSE)
    ->execute();

  $nodes = Node::loadMultiple($nids);

  foreach ($nodes as $node) {
    if ($node->hasField('field_tag_contrib') && $node->hasField('field_tags_contrib')) {
      $old_values = $node->get('field_tag_contrib')->getValue();
      $node->set('field_tags_contrib', $old_values);
      $node->set('field_tag_contrib', []);
      $node->save();
    }
  }

  \Drupal::messenger()->addMessage('Migrated field_tag_contrib values to field_tags_contrib.');
}

/*
 * create users for all youtube channels
**/
function ish_drupal_module_update_9003() {
  $nids = \Drupal::entityQuery('node')
    ->condition('type', 'youtube_channel')
    ->accessCheck(FALSE)
    ->execute();

  foreach ($nids as $nid) {
    $ch = new YoutubeChannel($nid);
    $ch->afterCreate();
  }
  \Drupal::messenger()->addMessage('created users for all youtube channels');
}

/*
 * create object3d
 * 2026-01-24
**/
function ish_drupal_module_update_9004() {
  if (!NodeType::load('object3d')) {
    $type = NodeType::create([
      'type' => 'object3d',
      'name' => 'Object3d',
      'description' => 'object3d',
    ]);
    $type->save();
  }
  $repo = \Drupal::service('entity_display.repository');
  $full_display = $repo->getViewDisplay('node', 'object3d', 'full');
  $form_display = $repo->getFormDisplay('node', 'object3d', 'default');

  if (!FieldStorageConfig::loadByName('node', 'field_width')) {
    FieldStorageConfig::create([
      'field_name' => 'field_width',
      'entity_type' => 'node',
      'type' => 'string',
      'cardinality' => 1,
      'settings' => [
        'max_length' => 10,
      ],
    ])->save();
  }
  if (!FieldConfig::loadByName('node', 'object3d', 'field_width')) {
    FieldConfig::create([
      'field_name' => 'field_width',
      'entity_type' => 'node',
      'bundle' => 'object3d',
      'label' => 'width',
      'required' => TRUE,
    ])->save();
  }
  $form_display->setComponent('field_width', [
    'type' => 'string_textfield',
    'weight' => 20,
    'settings' => [],
  ]);
  $form_display->save();
  $field = FieldConfig::loadByName('node', 'object3d', 'field_width');
  $field->setDefaultValue([
    [ 'value' => '500px' ],
  ]);
  $field->save();


  if (!FieldStorageConfig::loadByName('node', 'field_height')) {
    FieldStorageConfig::create([
      'field_name' => 'field_height',
      'entity_type' => 'node',
      'type' => 'string',
      'cardinality' => 1,
      'settings' => [
        'max_length' => 10,
      ],
    ])->save();
  }
  if (!FieldConfig::loadByName('node', 'object3d', 'field_height')) {
    FieldConfig::create([
      'field_name' => 'field_height',
      'entity_type' => 'node',
      'bundle' => 'object3d',
      'label' => 'height',
      'required' => TRUE,
    ])->save();
  }
  $form_display->setComponent('field_height', [
    'type' => 'string_textfield',
    'weight' => 21,
    'settings' => [],
  ]);
  $form_display->save();
  $field = FieldConfig::loadByName('node', 'object3d', 'field_height');
  $field->setDefaultValue([
    [ 'value' => '400px' ],
  ]);
  $field->save();


  if (!FieldConfig::loadByName('node', 'object3d', 'field_vote_up_down')) {
    FieldConfig::create([
      'field_name' => 'field_vote_up_down',
      'entity_type' => 'node',
      'bundle' => 'object3d',
      'label' => 'Vote Up Down',
      'required' => FALSE,
    ])->save();
  }
  $full_display->setComponent('field_vote_up_down', [
    'label' => 'hidden',
    'settings' => [
      'vote_up_down_formatter_type' => 'thumbs',
    ],
    'type' => 'vote_up_down_formatter_type',
    'weight' => -10,
  ]);
  $full_display->save();


  if (!FieldConfig::loadByName('node', 'object3d', 'field_image_thumb')) {
    FieldConfig::create([
      'bundle' => 'object3d',
      'entity_type' => 'node',
      'field_name' => 'field_image_thumb',
      'label' => 'Image Thumb',
      'required' => FALSE,
      'settings' => [
        'alt_field' => TRUE,
        'alt_field_required' => FALSE,
      ],
    ])->save();
  }
  $form_display->setComponent('field_image_thumb', [
    'type' => 'file_generic',
    'weight' => 25,
    'settings' => [
      // 'alt_field' => TRUE,
      // 'alt_field_required' => FALSE,
    ],
  ]);
  $form_display->save();
  $full_display->setComponent('field_image_thumb', [
    'label' => 'hidden',
    'weight' => -10,
  ]);
  $full_display->save();


  if (!FieldConfig::loadByName('node', 'object3d', 'field_tags_contrib')) {
    FieldConfig::create([
      'field_name' => 'field_tags_contrib',
      'entity_type' => 'node',
      'bundle' => 'object3d',
      'label' => 'Tags Contrib',
      'required' => FALSE,
    ])->save();
  }
  $form_display->setComponent('field_tags_contrib', [
    'type' => 'options_buttons',
    'weight' => 23,
    'settings' => [],
  ]);
  $form_display->save();
  $full_display->setComponent('field_tags_contrib', [
    'label' => 'hidden',
    'weight' => -10,
  ]);
  $full_display->save();


  if (!Vocabulary::load('tags_issue')) {
    Vocabulary::create([
      'vid' => 'tags_issue',
      'description' => 'Tags Issue',
      'name' => 'Tags Issue',
    ])->save();
  }
  if (!FieldStorageConfig::loadByName('node', 'field_tags_issue')) {
    FieldStorageConfig::create([
      'field_name' => 'field_tags_issue',
      'entity_type' => 'node',
      'type' => 'entity_reference',
      'cardinality' => -1,
      'settings' => [
        'target_type' => 'taxonomy_term',
      ],
    ])->save();
  }
  if (!FieldConfig::loadByName('node', 'object3d', 'field_tags_issue')) {
    FieldConfig::create([
      'field_name' => 'field_tags_issue',
      'entity_type' => 'node',
      'bundle' => 'object3d',
      'label' => 'Tags Issue',
      'required' => FALSE,
      'settings' => [
        'handler' => 'default:taxonomy_term',
        'handler_settings' => [
          'target_bundles' => [
            'tags_issue' => 'tags_issue',
          ],
          'auto_create' => FALSE,
        ],
      ],
    ])->save();
  }
  $form_display->setComponent('field_tags_issue', [
    'type' => 'options_buttons',
    'weight' => 24,
    'settings' => [],
  ]);
  $form_display->save();


  if (!FieldStorageConfig::loadByName('node', 'field_model')) {
    FieldStorageConfig::create([
      'field_name' => 'field_model',
      'entity_type' => 'node',
      'type' => 'file',
      'cardinality' => 1,
      'settings' => [
        'uri_scheme' => 'public',
        'file_extensions' => 'glb obj',
        'max_filesize' => '50 MB',
      ],
    ])->save();
  }
  if (!FieldConfig::loadByName('node', 'object3d', 'field_model')) {
    FieldConfig::create([
      'field_name' => 'field_model',
      'entity_type' => 'node',
      'bundle' => 'object3d',
      'label' => 'Model',
      'required' => TRUE,
      'settings' => [
        'description_field' => TRUE,
        'file_extensions' => 'glb obj',
      ],
    ])->save();
  }
  $form_display->setComponent('field_model', [
    'type' => 'file_generic',
    'weight' => 25,
    'settings' => [],
  ]);
  $form_display->save();
  $full_display->setComponent('field_model', [
    'label' => 'hidden',
    'type' => 'file_url_plain',
    'weight' => -10,
  ]);
  $full_display->save();
}

/*
 * create scene3d
 * 2026-01-25
**/
function ish_drupal_module_update_9013() {
  if (!NodeType::load('scene3d')) {
    $type = NodeType::create([
      'type' => 'scene3d',
      'name' => 'scene3d',
      'description' => 'scene3d',
    ]);
    $type->save();
  }
  $repo = \Drupal::service('entity_display.repository');
  $full_display = $repo->getViewDisplay('node', 'scene3d', 'full');
  $form_display = $repo->getFormDisplay('node', 'scene3d', 'default');

  if (!FieldStorageConfig::loadByName('node', 'field_width')) {
    FieldStorageConfig::create([
      'field_name' => 'field_width',
      'entity_type' => 'node',
      'type' => 'string',
      'cardinality' => 1,
      'settings' => [
        'max_length' => 10,
      ],
    ])->save();
  }
  if (!FieldConfig::loadByName('node', 'scene3d', 'field_width')) {
    FieldConfig::create([
      'field_name' => 'field_width',
      'entity_type' => 'node',
      'bundle' => 'scene3d',
      'label' => 'width',
      'required' => TRUE,
    ])->save();
  }
  $form_display->setComponent('field_width', [
    'type' => 'string_textfield',
    'weight' => 20,
    'settings' => [],
  ]);
  $form_display->save();
  $field = FieldConfig::loadByName('node', 'scene3d', 'field_width');
  $field->setDefaultValue([
    [ 'value' => '500px' ],
  ]);
  $field->save();


  if (!FieldStorageConfig::loadByName('node', 'field_height')) {
    FieldStorageConfig::create([
      'field_name' => 'field_height',
      'entity_type' => 'node',
      'type' => 'string',
      'cardinality' => 1,
      'settings' => [
        'max_length' => 10,
      ],
    ])->save();
  }
  if (!FieldConfig::loadByName('node', 'scene3d', 'field_height')) {
    FieldConfig::create([
      'field_name' => 'field_height',
      'entity_type' => 'node',
      'bundle' => 'scene3d',
      'label' => 'height',
      'required' => TRUE,
    ])->save();
  }
  $form_display->setComponent('field_height', [
    'type' => 'string_textfield',
    'weight' => 21,
    'settings' => [],
  ]);
  $form_display->save();
  $field = FieldConfig::loadByName('node', 'scene3d', 'field_height');
  $field->setDefaultValue([
    [ 'value' => '400px' ],
  ]);
  $field->save();


  if (!FieldConfig::loadByName('node', 'scene3d', 'field_vote_up_down')) {
    FieldConfig::create([
      'field_name' => 'field_vote_up_down',
      'entity_type' => 'node',
      'bundle' => 'scene3d',
      'label' => 'Vote Up Down',
      'required' => FALSE,
    ])->save();
  }
  $full_display->setComponent('field_vote_up_down', [
    'label' => 'hidden',
    'settings' => [
      'vote_up_down_formatter_type' => 'thumbs',
    ],
    'type' => 'vote_up_down_formatter_type',
    'weight' => -10,
  ]);
  $full_display->save();


  if (!FieldConfig::loadByName('node', 'scene3d', 'field_image_thumb')) {
    FieldConfig::create([
      'bundle' => 'scene3d',
      'entity_type' => 'node',
      'field_name' => 'field_image_thumb',
      'label' => 'Image Thumb',
      'required' => FALSE,
      'settings' => [
        'alt_field' => TRUE,
        'alt_field_required' => FALSE,
      ],
    ])->save();
  }
  $form_display->setComponent('field_image_thumb', [
    'type' => 'file_generic',
    'weight' => 25,
    'settings' => [],
  ]);
  $form_display->save();
  $full_display->setComponent('field_image_thumb', [
    'label' => 'hidden',
    'weight' => -10,
  ]);
  $full_display->save();

  if (!Vocabulary::load('tags_contrib')) {
    Vocabulary::create([
      'vid' => 'tags_contrib',
      'description' => 'tags_contrib',
      'name' => 'tags_contrib',
    ])->save();
  }
  if (!FieldConfig::loadByName('node', 'scene3d', 'field_tags_contrib')) {
    FieldConfig::create([
      'field_name' => 'field_tags_contrib',
      'entity_type' => 'node',
      'bundle' => 'scene3d',
      'label' => 'Tags Contrib',
      'required' => FALSE,
      'settings' => [
        'handler' => 'default:taxonomy_term',
        'handler_settings' => [
          'target_bundles' => [
            'tags_contrib' => 'tags_contrib',
          ],
          'auto_create' => FALSE,
        ],
      ],
    ])->save();
  }
  $form_display->setComponent('field_tags_contrib', [
    'type' => 'options_buttons',
    'weight' => 23,
    'settings' => [],
  ]);
  $form_display->save();
  $full_display->setComponent('field_tags_contrib', [
    'label' => 'hidden',
    'weight' => -10,
  ]);
  $full_display->save();


  if (!Vocabulary::load('tags_issue')) {
    Vocabulary::create([
      'vid' => 'tags_issue',
      'description' => 'tags_issue',
      'name' => 'tags_issue',
    ])->save();
  }
  if (!FieldStorageConfig::loadByName('node', 'field_tags_issue')) {
    FieldStorageConfig::create([
      'field_name' => 'field_tags_issue',
      'entity_type' => 'node',
      'type' => 'entity_reference',
      'cardinality' => -1,
      'settings' => [
        'target_type' => 'taxonomy_term',
      ],
    ])->save();
  }
  if (!FieldConfig::loadByName('node', 'scene3d', 'field_tags_issue')) {
    FieldConfig::create([
      'field_name' => 'field_tags_issue',
      'entity_type' => 'node',
      'bundle' => 'scene3d',
      'label' => 'Tags Issue',
      'required' => FALSE,
      'settings' => [
        'handler' => 'default:taxonomy_term',
        'handler_settings' => [
          'target_bundles' => [
            'tags_issue' => 'tags_issue',
          ],
          'auto_create' => FALSE,
        ],
      ],
    ])->save();
  }
  $form_display->setComponent('field_tags_issue', [
    'type' => 'options_buttons',
    'weight' => 24,
    'settings' => [],
  ]);
  $form_display->save();


  if (!FieldStorageConfig::loadByName('node', 'field_model')) {
    FieldStorageConfig::create([
      'field_name' => 'field_model',
      'entity_type' => 'node',
      'type' => 'file',
      'cardinality' => 1,
      'settings' => [
        'uri_scheme' => 'public',
        'file_extensions' => 'glb obj',
        'max_filesize' => '50 MB',
      ],
    ])->save();
  }
  if (!FieldConfig::loadByName('node', 'scene3d', 'field_model')) {
    FieldConfig::create([
      'field_name' => 'field_model',
      'entity_type' => 'node',
      'bundle' => 'scene3d',
      'label' => 'Model',
      'required' => TRUE,
      'settings' => [
        'description_field' => TRUE,
        'file_extensions' => 'glb obj',
      ],
    ])->save();
  }
  $form_display->setComponent('field_model', [
    'type' => 'file_generic',
    'weight' => 25,
    'settings' => [],
  ]);
  $form_display->save();
  $full_display->setComponent('field_model', [
    'label' => 'hidden',
    'type' => 'file_url_plain',
    'weight' => -10,
  ]);
  $full_display->save();
}

/*
 * create x, y, z fields for object3d
**/
function ish_drupal_module_update_9018() {
  $form_display = EntityFormDisplay::load('node.object3d.default')
    ?: EntityFormDisplay::create([
      'targetEntityType' => 'node',
      'bundle' => 'object3d',
      'mode' => 'default',
      'status' => TRUE,
    ]);
  $view_display = EntityViewDisplay::load('node.object3d.full')
    ?: EntityViewDisplay::create([
      'targetEntityType' => 'node',
      'bundle' => 'object3d',
      'mode' => 'full',
      'status' => TRUE,
    ]);
  $fields = ['x', 'y', 'z'];

  foreach ($fields as $axis) {
    if (!FieldStorageConfig::loadByName('node', 'field_' . $axis)) {
      FieldStorageConfig::create([
        'field_name' => 'field_' . $axis,
        'entity_type' => 'node',
        'type' => 'string',
        'settings' => [
          'max_length' => 20,
        ],
      ])->save();
    }

    if (!FieldConfig::loadByName('node', 'object3d', 'field_' . $axis)) {
      FieldConfig::create([
        'field_name' => 'field_' . $axis,
        'entity_type' => 'node',
        'bundle' => 'object3d',
        'label' => strtoupper($axis),
      ])->save();
    }

    $form_display->setComponent('field_' . $axis, [
      'type' => 'string_textfield',
      'weight' => 0,
    ]);
    $form_display->save();

    $view_display->setComponent('field_' . $axis, [
      'type' => 'string',
      'label' => 'above',
      'weight' => 0,
    ]);
    $view_display->save();
  }


}
/* Create view mode 'touch'
 * Actually I think I don't need it?
 * 2026-01-25
**/
/*
function ish_drupal_module_update_9015() {
  if (!EntityViewMode::load('node.touch')) {
    EntityViewMode::create([
      'id' => 'node.touch',
      'label' => 'touch',
      'targetEntityType' => 'node',
      'status' => TRUE,
    ])->save();
  }
  $display = EntityViewDisplay::load('node.scene3d.touch');
  if (!$display) {
    EntityViewDisplay::create([
      'targetEntityType' => 'node',
      'bundle' => 'scene3d',
      'mode' => 'touch',
      'status' => TRUE,
    ])->save();
  }
}
*/

/*
 * allow anonymous to view user profiles
**/
function ish_drupal_module_update_9019() {
  $role = \Drupal\user\Entity\Role::load('anonymous');
  if ($role && !$role->hasPermission('access user profiles')) {
    $role->grantPermission('access user profiles')->save();
  }
}


