<?php

use Drupal\ish_drupal_module\Config\BlocksConfig;
use Drupal\ish_drupal_module\Config\ContentTypesConfig;
use Drupal\ish_drupal_module\Config\DefaultFields;
use Drupal\ish_drupal_module\Config\LayoutConfig;
use Drupal\ish_drupal_module\Config\ModulesConfig;
use Drupal\ish_drupal_module\Config\SectionsConfig;
use Drupal\ish_drupal_module\Config\ThisConfig;
use Drupal\ish_drupal_module\Config\ViewsConfig;

/*
 * reset the counter:
 *   drush -l wco.local php:eval "\Drupal::keyValue('system.schema')->delete('ish_drupal_module');"
 * check the counter:
 *   drush -l wco.local php:eval "print \Drupal::keyValue('system.schema')->get('ish_drupal_module');"
**/

/*
**/
function ish_drupal_module_update_9016() {
  ThisConfig::do_initial_setup();
}

function ish_drupal_module_update_9015() {
  // BlocksConfig::setup_about_10();

}






