
ish_drupal_module.settings:
  type: config_object
  label: 'My Ish Settings'
  mapping:
    google_api_youtube_key:
      type: string
      label: 'Google Api Youtube Key'
    libretranslate_api_key:
      type: string
      label: 'libretranslate_api_key'
    llm_api_key:
      type: string
      label: 'llm_api_key'
